import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google";
import StoreProvider from "@/app/StoreProvider";
import ScrollToTop from "@/services/scroolToTop/scroolToTop";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import "./index.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}>
    <html className="scroll-smooth" lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <StoreProvider>
        {children}
        <Toaster position="top-center" reverseOrder={false} />
        <ScrollToTop />
        </StoreProvider>
      </body>
    </html>
    </GoogleOAuthProvider>
  );
}
